/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:130d7902-c151-4f15-8dba-e17c94efe198",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_CvzuVqNyf",
    "aws_user_pools_web_client_id": "2e76rs3tkbpf30imkqemffldni",
    "oauth": {}
};


export default awsmobile;
